blank_issues_enabled: false

contact_links:
  - name: PyQtUI Widgets ğŸª°
    url: https://github.com/djoezeke/pyqtui
    about: Modern Widgets for PyQT and Pyside.

  - name: PyQtUI Issues ğŸ
    url: https://github.com/djoezeke/pyqtui/issues
    about: Please report issues and vulnerabilities here.

  - name: PyQtUI Releases ğŸ’–
    url: https://github.com/djoezeke/pyqtui/releases
    about: Please latest PyQtUI release here.
