name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.0.0
      - "v*" # Push events to matching v*, i.e. v1.0.0

    # branches: "release/**"

jobs:
  release-build:
    name: Build Distributions

    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Uv & Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Package dependencies
        run: |
          uv sync

      - name: Build distributions
        run: |
          uv build
          uv run twine check dist/* || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    name: Create Release

    needs:
      - release-build

    permissions:
      id-token: write
      contents: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Get Release Version
        id: version
        run: echo "VER=${GITHUB_REF_NAME#'refs/tags/'}" >> $GITHUB_OUTPUT

      - name: Generate Release Attestation
        uses: actions/attest-build-provenance@v3.0.0
        with:
          subject-path: "dist/*"

      - name: Create Tag Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: TKinterUI ${{ steps.version.outputs.VER }} release
          tag_name: ${{ contains(steps.version.outputs.VER, 'dev') }}
          prerelease: ${{ contains(steps.version.outputs.VER, 'dev') }}
          # target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          # draft: true
          files: dist/*
